# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db74f30453b48e064d4dc90826f3c99cff4e3317da6c7a097cd5efdcf84873281387b090ead85feeed813d32a04fd2283508e410911bab7fc108fd5b00b1fc3f

test:
  secret_key_base: f33d781ab7e6eee89b864e1107fedbc05a968bfc50510f74e4757571fc3b7c3251c203f90bbec09d45f653381d17681acf19812057ba139b1e93db0d487fcab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
